### ISSUE TITLE
No se puede ingresar a la page

### ISSUE THREAD

**Issue by FacundoEG** [FefeGalaxy/desafio-modulo-3#1]
Hola Fefe! fíjate que en el repositorio no dejaste el link para poder ingresar a la pagina con github pages.

Acodate que para que lo puedan aprobar y revisarlo, tenes que tener la pagina subida y funcional!

Te voy a dejar el desafío sin corregir hasta que puedas solucionar eso.

Saludos!

**Comment by FefeGalaxy** [comment]
Uuuhh cierto, ya lo modifico, graciasEl 2 sep. 2021 1:24 p. m., Facundo Graña ***@***.***> escribió:

Hola Fefe! fíjate que en el repositorio no dejaste el link para poder ingresar a la pagina con github pages.

Acodate que para que lo puedan aprobar y revisarlo, tenes que tener la pagina subida y funcional!

Te voy a dejar el desafío sin corregir hasta que puedas solucionar eso.

Saludos!

**Comment by FefeGalaxy** [comment]
Hola! Ya está actualizado, vuelvo a mandar el link del desafioEl 2 sep. 2021 1:34 p. m., federico escalada ***@***.***> escribió:Uuuhh cierto, ya lo modifico, graciasEl 2 sep. 2021 1:24 p. m., Facundo Graña ***@***.***> escribió:

Hola Fefe! fíjate que en el repositorio no dejaste el link para poder ingresar a la pagina con github pages.

Acodate que para que lo puedan aprobar y revisarlo, tenes que tener la pagina subida y funcional!

Te voy a dejar el desafío sin corregir hasta que puedas solucionar eso.

Saludos!

**Comment by FacundoEG** [comment]
Dale Fefe, cierro issue entonces.
