### ISSUE TITLE
Se rompe el diseño en modo desktop

### ISSUE THREAD

**Issue by FacundoEG** [FefeGalaxy/desafio-modulo-3#3]
Fede ahi lo pude abrir y voy a comentar unas cositas mas aparte de lo que te pusieron en el issue de abajo!

Mira, para empezar, fijate en modo desktop que se desacomoda toda la section-1, te sugeriria que en la foto trates de usar un margen en porcentajes asi se va corriendo, ya que en 1400px nisiquiera aparece dentro de la pantalla:

![image](https://user-images.githubusercontent.com/79592789/131928889-c652e2c2-0449-40a0-97f2-b9d6b3dfd953.png)

En la parte del header donde van los servicios y etc, pusiste un div con texto y por eso cuando achicas la resolucion se superponen abajo. Te recomiendo que uses un div por cada elemento y los vayas acomodando de una forma mas prolija.
(desde los 1000px de ancho quedan "bien", pero tenes que considerar que queden acomodados desde que cambia la resolución de mobile a desktop)

![image](https://user-images.githubusercontent.com/79592789/131929080-d080547d-aa84-4ab6-b49a-16b9f89c46b1.png)

Tambien noto que suele suceder algo parecido en la section-2, donde margenes muy amplios y fijos y dificulta que los elementos se acomoden bien:

![image](https://user-images.githubusercontent.com/79592789/131929152-8bcbcd0a-866b-43e4-aa56-a81f640ffcdb.png)

En resumen, te aconsejo que vayas acomodando los elementos de una forma que se vayan moviendo gradualmente, no usando margenes fijos ni estaticos, ya que pensa que dichos elementos deben ir acompañando la resolucion. La cual no va a tener siempre el mismo ancho para todas las pantallas.

Te pediría que revises esas cuestiones y vuelvas a mandar el desafío!
Cualquier duda coméntanos por aca o pregunta en discord que con gusto te ayudamos!

Saludos!

**Comment by FefeGalaxy** [comment]
Hola buenas, ya está todo hecho con porcentajes y más ordenado, no sé si el link de la página está actualizado, pero ya están hechos todos los cambios El 2 sep. 2021 8:39 p. m., Facundo Graña ***@***.***> escribió:

Fede ahi lo pude abrir y voy a comentar unas cositas mas aparte de lo que te pusieron en el issue de abajo!

Mira, para empezar, fijate en modo desktop que se desacomoda toda la section-1, te sugeriria que en la foto trates de usar un margen en porcentajes asi se va corriendo, ya que en 1400px nisiquiera aparece dentro de la pantalla:



En la parte del header donde van los servicios y etc, pusiste un div con texto y por eso cuando achicas la resolucion se superponen abajo. Te recomiendo que uses un div por cada elemento y los vayas acomodando de una forma mas prolija.

(desde los 1000px de ancho quedan "bien", pero tenes que considerar que queden acomodados desde que cambia la resolución de mobile a desktop)



Tambien noto que suele suceder algo parecido en la section-2, donde margenes muy amplios y fijos y dificulta que los elementos se acomoden bien:



En resumen, te recomiendo que vayas acomodando los elementos de una forma que se vayan moviendo gradualmente, no usando margenes fijos ni estaticos, ya que pensa que dichos elementos deben ir acompañando la resolción. La cual no va a tener siempre el mismo ancho para todas las pantallas.

Te sugiero que revises esas cuestiones y vuelvas a mandar el desafío!

Cualquier duda comentanos por aca o pregunta en discord que con gusto te ayudamos! Saludos!

**Comment by FefeGalaxy** [comment]
Porque cuando entro al link, está todo desacomodado y mal hecho como antes, pero yo modifique todo, está todo nuevo en el commit llamado "Listo"El 3 sep. 2021 2:10 p. m., federico escalada ***@***.***> escribió:Hola buenas, ya está todo hecho con porcentajes y más ordenado, no sé si el link de la página está actualizado, pero ya están hechos todos los cambios El 2 sep. 2021 8:39 p. m., Facundo Graña ***@***.***> escribió:

Fede ahi lo pude abrir y voy a comentar unas cositas mas aparte de lo que te pusieron en el issue de abajo!

Mira, para empezar, fijate en modo desktop que se desacomoda toda la section-1, te sugeriria que en la foto trates de usar un margen en porcentajes asi se va corriendo, ya que en 1400px nisiquiera aparece dentro de la pantalla:



En la parte del header donde van los servicios y etc, pusiste un div con texto y por eso cuando achicas la resolucion se superponen abajo. Te recomiendo que uses un div por cada elemento y los vayas acomodando de una forma mas prolija.

(desde los 1000px de ancho quedan "bien", pero tenes que considerar que queden acomodados desde que cambia la resolución de mobile a desktop)



Tambien noto que suele suceder algo parecido en la section-2, donde margenes muy amplios y fijos y dificulta que los elementos se acomoden bien:



En resumen, te recomiendo que vayas acomodando los elementos de una forma que se vayan moviendo gradualmente, no usando margenes fijos ni estaticos, ya que pensa que dichos elementos deben ir acompañando la resolción. La cual no va a tener siempre el mismo ancho para todas las pantallas.

Te sugiero que revises esas cuestiones y vuelvas a mandar el desafío!

Cualquier duda comentanos por aca o pregunta en discord que con gusto te ayudamos! Saludos!
